name: pulse_now_assessment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  
  # HTTP
  http: ^1.1.0
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Utilities
  intl: ^0.18.1

  # Web Socket
  web_socket_channel: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
